# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

betampt <- function(M, L, nthin, H, a, b, c, map, shape, rate) {
    .Call(`_TreeBUGS_betampt`, M, L, nthin, H, a, b, c, map, shape, rate)
}

simplempt <- function(M, L, nthin, H, a, b, c, map, alpha, beta) {
    .Call(`_TreeBUGS_simplempt`, M, L, nthin, H, a, b, c, map, alpha, beta)
}

loglikMPT <- function(theta, h, a, b, c, map) {
    .Call(`_TreeBUGS_loglikMPT`, theta, h, a, b, c, map)
}

