# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sliceAB <- function(x, fixed, theta, shape = 1., rate = .05, eps = .01, steps = 5000L) {
    .Call('TreeBUGS_sliceAB', PACKAGE = 'TreeBUGS', x, fixed, theta, shape, rate, eps, steps)
}

betampt <- function(M, H, a, b, c, map, shape = 1., rate = .1) {
    .Call('TreeBUGS_betampt', PACKAGE = 'TreeBUGS', M, H, a, b, c, map, shape, rate)
}

